### ISSUE TITLE
BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!

### ISSUE THREAD

**Issue by lfoppiano** [RohanNagar/thunder#1429]
**Description**
I'm not sure it's a bug. 

However, I'm running a dropwizard application which I've just updated to dropwizard 2.1. I'm also using 

    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    implementation 'com.fasterxml.jackson.module:jackson-module-afterburner:2.13.0'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3'

I'm using afterburner and jdk 8 and I get `com.fasterxml.jackson.module.blackbird.BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!` seee below for the full stacktrace. 

**Reproduce steps**
1. Run the application using java 8 
2. An exception is thrown: 
```WARN  [2022-05-23 16:03:31,703] com.fasterxml.jackson.module.blackbird.BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!
! java.lang.NoSuchMethodError: java.lang.invoke.MethodHandles.privateLookupIn(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;
! at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
! at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
! at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
! ... 28 common frames omitted
! Causing: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandles.privateLookupIn(Class,Lookup)Lookup/invokeStatic
! at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
! at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
! at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
! at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.init(ReflectionHack.java:39)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.<clinit>(ReflectionHack.java:34)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack.privateLookupIn(ReflectionHack.java:24)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.lambda$findProperties$0(BBSerializerModifier.java:67)
! at com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$runnable$0(Unchecked.java:31)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.findProperties(BBSerializerModifier.java:68)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.changeProperties(BBSerializerModifier.java:52)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:414)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:294)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:239)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
! at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
! at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
! at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
! at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
! at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4519)
! at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4498)
! at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
! at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:76)
! at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
! at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
! at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:137)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.grobid.service.main.GrobidQuantitiesApplication.main(GrobidQuantitiesApplication.java:89)
```
4. if the application is ran with jdk 11, there is no problem. 

**Additional context**
I would like to understand what is the issue and how to solve it. 

Thank you in advance

**Comment by RohanNagar** [comment]
Hi @lfoppiano, you should open an issue with https://github.com/dropwizard/dropwizard, it looks specific to dropwizard and not the thunder application.

**Comment by lfoppiano** [comment]
Dear @RohanNagar sorry about that. Indeed it does have nothing to do with this project. 
I'm sorry. I honestly did not realise I opened here...
