### ISSUE TITLE
Return response when DynamoDB is down instead of throwing exception

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#3]
If Thunder is unable to access DynamoDB for any reason, it throws a bunch of exceptions and eventually the server returns a 500 response code instead of something more appropriate.

```
INFO  [2016-01-24 01:23:29,715] com.amazonaws.http.AmazonHttpClient: Unable to execute HTTP request: Connection refused
! java.net.ConnectException: Connection refused
! at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_51]
! at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_51]
! at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_51]
! at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_51]
! at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_51]
```

**Comment by RohanNagar** [comment]
After some investigation, looks like we just need to surround our calls to DynamoDB in the DAO with a try/catch for `AmazonClientException`. Then we can return or throw our own exception in order to propagate this error up to `UserResource`.
